//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appVuelaSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public equipaje()
        {
            this.vuelo = new HashSet<vuelo>();
        }
    
        public decimal idequipaje { get; set; }
        public decimal idcliente { get; set; }
        public decimal peso { get; set; }
        public string descripcion { get; set; }
        public decimal idViaje { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual viaje viaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vuelo> vuelo { get; set; }
    }
}
