//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appVuelaSA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class proyecto2RequeEntities : DbContext
    {
        public proyecto2RequeEntities()
            : base("name=proyecto2RequeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aeropuerto> aeropuerto { get; set; }
        public virtual DbSet<asiento> asiento { get; set; }
        public virtual DbSet<avion> avion { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<equipaje> equipaje { get; set; }
        public virtual DbSet<pasajeabordar> pasajeabordar { get; set; }
        public virtual DbSet<reservacion> reservacion { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<viaje> viaje { get; set; }
        public virtual DbSet<viajevuelo> viajevuelo { get; set; }
        public virtual DbSet<vuelo> vuelo { get; set; }
        public virtual DbSet<Vista_Viaje> Vista_Viaje { get; set; }
    
        public virtual ObjectResult<Asientos_Por_Vuelo_Result> Asientos_Por_Vuelo(Nullable<decimal> idVuelo)
        {
            var idVueloParameter = idVuelo.HasValue ?
                new ObjectParameter("idVuelo", idVuelo) :
                new ObjectParameter("idVuelo", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Asientos_Por_Vuelo_Result>("Asientos_Por_Vuelo", idVueloParameter);
        }
    
        public virtual ObjectResult<Viajes_Result> Viajes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Viajes_Result>("Viajes");
        }
    
        public virtual ObjectResult<Vuelos_Por_Viaje_Result> Vuelos_Por_Viaje(Nullable<decimal> idViaje)
        {
            var idViajeParameter = idViaje.HasValue ?
                new ObjectParameter("idViaje", idViaje) :
                new ObjectParameter("idViaje", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Vuelos_Por_Viaje_Result>("Vuelos_Por_Viaje", idViajeParameter);
        }
    }
}
