//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appVuelaSA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class proyectoRequeEntities : DbContext
    {
        public proyectoRequeEntities()
            : base("name=proyectoRequeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aeropuerto> aeropuerto { get; set; }
        public virtual DbSet<asiento> asiento { get; set; }
        public virtual DbSet<avion> avion { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<equipaje> equipaje { get; set; }
        public virtual DbSet<pasajeabordar> pasajeabordar { get; set; }
        public virtual DbSet<reservacion> reservacion { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<viaje> viaje { get; set; }
        public virtual DbSet<viajevuelo> viajevuelo { get; set; }
        public virtual DbSet<vuelo> vuelo { get; set; }
        public virtual DbSet<Vista_Viaje> Vista_Viaje { get; set; }
    
        public virtual ObjectResult<Asientos_Por_Vuelo_Result> Asientos_Por_Vuelo(Nullable<decimal> idVuelo)
        {
            var idVueloParameter = idVuelo.HasValue ?
                new ObjectParameter("idVuelo", idVuelo) :
                new ObjectParameter("idVuelo", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Asientos_Por_Vuelo_Result>("Asientos_Por_Vuelo", idVueloParameter);
        }
    
        public virtual ObjectResult<Historial_Vuelos_Result> Historial_Vuelos(Nullable<decimal> idcliente)
        {
            var idclienteParameter = idcliente.HasValue ?
                new ObjectParameter("idcliente", idcliente) :
                new ObjectParameter("idcliente", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Historial_Vuelos_Result>("Historial_Vuelos", idclienteParameter);
        }
    
        public virtual ObjectResult<Proximos_Vuelos_Result> Proximos_Vuelos(Nullable<decimal> idCliente)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("idCliente", idCliente) :
                new ObjectParameter("idCliente", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proximos_Vuelos_Result>("Proximos_Vuelos", idClienteParameter);
        }
    
        public virtual int Validar_LogIn(string nombreUsuario, string contrasenna, ObjectParameter output)
        {
            var nombreUsuarioParameter = nombreUsuario != null ?
                new ObjectParameter("nombreUsuario", nombreUsuario) :
                new ObjectParameter("nombreUsuario", typeof(string));
    
            var contrasennaParameter = contrasenna != null ?
                new ObjectParameter("contrasenna", contrasenna) :
                new ObjectParameter("contrasenna", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Validar_LogIn", nombreUsuarioParameter, contrasennaParameter, output);
        }
    
        public virtual ObjectResult<Viajes_Result> Viajes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Viajes_Result>("Viajes");
        }
    
        public virtual ObjectResult<Viajes_Por_Origen_Destino_Result> Viajes_Por_Origen_Destino(Nullable<decimal> origen, Nullable<decimal> destino)
        {
            var origenParameter = origen.HasValue ?
                new ObjectParameter("origen", origen) :
                new ObjectParameter("origen", typeof(decimal));
    
            var destinoParameter = destino.HasValue ?
                new ObjectParameter("destino", destino) :
                new ObjectParameter("destino", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Viajes_Por_Origen_Destino_Result>("Viajes_Por_Origen_Destino", origenParameter, destinoParameter);
        }
    
        public virtual ObjectResult<Vuelos_Por_Viaje_Result> Vuelos_Por_Viaje(Nullable<decimal> idViaje)
        {
            var idViajeParameter = idViaje.HasValue ?
                new ObjectParameter("idViaje", idViaje) :
                new ObjectParameter("idViaje", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Vuelos_Por_Viaje_Result>("Vuelos_Por_Viaje", idViajeParameter);
        }
    }
}
