//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appVuelaSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pasajeabordar
    {
        public decimal idpasajeabordar { get; set; }
        public decimal idreservacion { get; set; }
        public System.DateTime fchpasaje { get; set; }
        public string estado { get; set; }
    
        public virtual reservacion reservacion { get; set; }
    }
}
