//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appVuelaSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pasajeabordar
    {
        public decimal idpasajeabordar { get; set; }
        public decimal idreservacion { get; set; }
        public System.DateTime fchpasaje { get; set; }
        public string estado { get; set; }
    
        public virtual reservacion reservacion { get; set; }
    }
}
