//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appVuelaSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public viaje()
        {
            this.equipaje = new HashSet<equipaje>();
            this.viajevuelo = new HashSet<viajevuelo>();
        }
    
        public decimal idviaje { get; set; }
        public System.DateTime horadepartida { get; set; }
        public System.DateTime horadellegada { get; set; }
        public decimal precio { get; set; }
        public string descripcion { get; set; }
        public decimal idaeropuertoorigen { get; set; }
        public decimal idaeropuertodestino { get; set; }
    
        public virtual aeropuerto aeropuerto { get; set; }
        public virtual aeropuerto aeropuerto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipaje> equipaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<viajevuelo> viajevuelo { get; set; }
    }
}
