//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appVuelaSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vista_Viaje
    {
        public decimal idViaje { get; set; }
        public System.DateTime horaDePartida { get; set; }
        public System.DateTime horaDeLlegada { get; set; }
        public decimal precio { get; set; }
        public string descripcion { get; set; }
        public decimal idAeropuertoOrigen { get; set; }
        public decimal idAeropuertoDestino { get; set; }
        public Nullable<int> escalas { get; set; }
    }
}
